<!-- This is the section of the homepage which displays all the NFTs of the collection
in the form of a grid of NFTItem components.  -->

<template>
<!-- We would like you to render 12 NFTs in the desktop full width view, but limit it to 3 NFTs if mobile width (examples in the design)-->
<!-- Here you will see conditional rendering separating between mobile Nfts and normal. You may use your own logic for displaying the nfts between the mobile view and desktop-->
    <div class="home-nft-display-container">
        <div class="nft-item-list" v-if="mobileNFTs && mobileNFTs.length > 0">
            <div v-for="(item, index) in mobileNFTs" :key="index"> <!--This will loop through all the items in mobileNFTs Array-->
            <!--Display and style as appropriate-->
              <NFTItem :data="item" />
            </div>
        </div>
        <div v-else>
            <!--You may display the normal NFTs as such -->
            <div v-for="(item, index) in NFTs" :key="index"> <!--This will loop through all the items in NFTs Array generated by the computed method and display what you want-->
                <!--Display and style as appropriate-->
            </div>
        </div>
    </div>
</template>

<script>
// This component imports the NFTItem component which is used to display
// the NFT data in the collection. It displays the NFT items in a grid
// format which is responsive to any screen size and will display less
// NFTs on each row when the screen gets thinner. It also stores the NFT
// data in the mobileNFTs array which contain each NFT as an object containing
// the key information about the NFT.

import NFTItem from './NFTItem.vue';

export default {
  name: 'Home-NFT-Display',
  data() {
    return{
      mobileNFTs: [
        {name: 'Squirtle Sniffing Flower', artist: 'John Smith', priceInSTX: 40, priceInDollars: 57, image: './nft-images/pokemon-nft-1.webp'},
        {name: 'Holographic Pikachu', artist: 'Bull Basoar', priceInSTX: 46, priceInDollars: 55, image: './nft-images/pokemon-nft-2.jpg'},
        {name: 'Pixel Art Charmander', artist: 'Bill Board', priceInSTX: 20, priceInDollars: 27, image: './nft-images/pokemon-nft-3.png'},
        {name: 'Bored Infernape', artist: 'Cynthia', priceInSTX: 100, priceInDollars: 115, image: './nft-images/pokemon-nft-4.webp'},
        {name: 'Floating Mew', artist: 'Professor Oak', priceInSTX: 60, priceInDollars: 68, image: './nft-images/pokemon-nft-5.webp'},
        {name: 'Rainbow Minecraft Pikachu', artist: 'Herobrine', priceInSTX: 30, priceInDollars: 38, image: './nft-images/pokemon-nft-6.jpg'},
        {name: 'Pretty Pokeball', artist: 'Jane Smith', priceInSTX: 70, priceInDollars: 82, image: './nft-images/pokemon-nft-7.gif'},
        {name: 'Weedle', artist: 'Bug Catcher Joe', priceInSTX: 10, priceInDollars: 15, image: './nft-images/pokemon-nft-8.jpg'},
        {name: 'Mewtwo Cool Art', artist: 'Giovanni', priceInSTX: 50, priceInDollars: 61, image: './nft-images/pokemon-nft-9.jpg'},
        ] // You may use this to display limited NFTs
    }
  },
  mounted () {
  },
  created () {
    window.addEventListener('resize', this.checkScreen) // On window resize: runs the checkScreen method
  },
  methods: {
    checkScreen () {
      // You will have to add to this method if you want the expected results. Or abandon it entirely and make your own
      this.windowWidth = window.innerWidth
      if (this.windowWidth <= 600) {
          // do something
      } else if (this.windowWidth > 600) {
          // do something
      }
    },
  },
  computed: {
    GenerateNFTData() {
      const NFTs = []
      // Generate NFT data and push into the NFT array
      // You can create a loop that loops through n NFTS generating the data with unique IDs
      // Use these generated NFTs to display on the market.
      /** NFT data should look something like:
       * name: 'NFT-1' where 1 is the value of i in your loop
       * artist: 'Unknown Artist'
       * price: 100 #you may keep this random
       * image: this should be any image of your choosing or selected from the shared XD file
       */
      return NFTs
    }
},
components: {
      NFTItem
    }
}
</script>

<style scoped>
.nft-item-list {
  width: 80%;
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  row-gap: 30px;
}

@media(max-width: 900px){
  .nft-item-list {
    grid-template-columns: 1fr 1fr;
  }
}

@media(max-width: 650px){
  .nft-item-list {
    grid-template-columns: 1fr;
  }
}

.home-nft-display-container {
  display: flex;
  align-items: center;
  justify-content: center;
  margin-top: 50px;
}
</style>